project(TOOLS_DEdit)

file(GLOB DEdit_SRC
     "*.h"
     "*.cpp"
)

find_package(SDL2 REQUIRED)

add_definitions(-D_AFX_NO_OCC_SUPPORT -DDIRECT3D_VERSION=0x0700 -DCMAKE_GENERATOR_PLATFORM=Win32 -DWIN32 -D_WINDOWS -DDIRECTEDITOR_BUILD -DSTDLITH_MFC -DBDEFS_MFC -DPRE_FLOAT -DPREPROCESSOR_BUILD -DNO_PRAGMA_LIBS -DLT15_COMPAT -D_AFXDLL -D_WIN32_WINNT=0x501 -D_SILENCE_STDEXT_HASH_DEPRECATION_WARNINGS -DUSE_ID3DXEFFECT)
link_directories("${CMAKE_CURRENT_SOURCE_DIR}/../shared/world/")

add_executable(${PROJECT_NAME} WIN32
	DEdit.cpp
	AllTextureDlg.cpp
	BaseImgDlg.cpp
	baserezdlg.cpp
	bindkeydlg.cpp
	ClassList.cpp
	ColorPicker.cpp
	ColorWell.cpp
	CylinderPrimDlg.cpp
	DEdit.cpp
	dedit_concommand.cpp
	ExportObjFile.cpp
	FilePalette.cpp
	globalhotkeydb.cpp
	hotkey.cpp
	hotkeydb.cpp
	ImportObjFileFormat.cpp
	keyconfigdlg.cpp
	LoadLTADialog.cpp
	MapTextureCoordsDlg.cpp
	ModelDlg.cpp
	mtreectl.cpp
	MultiLineStringDlg.cpp
	NodeView.cpp
	NodeViewTreeCtrl.cpp
	ObjectImporter.cpp
	OptionsSheet.cpp
	PaletteEdit.cpp
	PrefabDlg.cpp
	ResizeDlg.cpp
	ResNewDir.cpp
	ResourceMgr.cpp
	RotateSelection.cpp
	SoundDlg.cpp
	SpriteDlg.cpp
	TextureDlg.cpp
	TextureProp.cpp
	UIEvent.cpp
	UndoPage.cpp
	UpdateAllObjects.cpp
	VectorButton.cpp
	VectorEdit.cpp
	WorldsDlg.cpp
	../../runtime/shared/src/converge.cpp
	../shared/engine/load_pcx.cpp
	Controls/ClassTree.cpp
	Controls/ColumnCtrl.cpp
	Controls/FrameList.cpp
	Controls/ProjectBar.cpp
	Controls/ProjectDirDlg.cpp
	Controls/ProjectTabControlBar.cpp
	Controls/ProjectTabCtrl.cpp
	Controls/PropEditString.cpp
	Controls/PropEditStringList.cpp
	Controls/ResizeBar.cpp
	Dlgs/AddObjectDlg.cpp
	Dlgs/AdvancedSelectDlg.cpp
	Dlgs/AdvancedSelectPropertyDlg.cpp
	Dlgs/AlphaFromColorDlg.cpp
	Dlgs/AutoTextureOptionsDlg.cpp
	Dlgs/CameraFOVDlg.cpp
	Dlgs/ClassDlg.cpp
	Dlgs/ClassListDlg.cpp
	Dlgs/ColorSelectDlg.cpp
	Dlgs/DebugDlg.cpp
	Dlgs/DirDialog.cpp
	Dlgs/EditEffectGroupDlg.cpp
	Dlgs/ErrorInformationDlg.cpp
	Dlgs/EventEditorDlg.cpp
	Dlgs/EventListDlg.cpp
	Dlgs/GenerateUniqueNamesDlg.cpp
	Dlgs/ImportBumpMapDlg.cpp
	Dlgs/ImportCubeMapDlg.cpp
	Dlgs/ImportObjectDlg.cpp
	Dlgs/LevelErrorDlg.cpp
	Dlgs/LevelErrorOptionsDlg.cpp
	Dlgs/LevelItemsDlg.cpp
	Dlgs/leveltexturesdlg.cpp
	Dlgs/LevelTexturesOptionsDlg.cpp
	Dlgs/LightAttenuation.cpp
	Dlgs/NameChangeReportDlg.cpp
	Dlgs/navigatordlg.cpp
	Dlgs/NavigatorStoreDlg.cpp
	Dlgs/NewProjectDlg.cpp
	Dlgs/ObjectBrowserDlg.cpp
	Dlgs/ObjectSearchDlg.cpp
	Dlgs/ObjectSelFilterDlg.cpp
	Dlgs/ObjectTrackerDlg.cpp
	Dlgs/PlanePrimitiveDlg.cpp
	Dlgs/PopupNoteDlg.cpp
	Dlgs/PrefabTrackerDlg.cpp
	Dlgs/PropertiesDlg.cpp
	Dlgs/PropPageDisplay.cpp
	Dlgs/PropPageOptionsClipboard.cpp
	Dlgs/PropPageOptionsControls.cpp
	Dlgs/PropPageOptionsD3D.cpp
	Dlgs/PropPageOptionsLighting.cpp
	Dlgs/PropPageOptionsMisc.cpp
	Dlgs/PropPageOptionsModels.cpp
	Dlgs/PropPageOptionsPrefabs.cpp
	Dlgs/PropPageOptionsRun.cpp
	Dlgs/RenameResourceDlg.cpp
	Dlgs/RotationEdit.cpp
	Dlgs/ScaleSelectDlg.cpp
	Dlgs/SelectEffectGroupDlg.cpp
	Dlgs/SolidAlphaDlg.cpp
	Dlgs/SpherePrimitiveDlg.cpp
	Dlgs/SpriteEditDlg.cpp
	Dlgs/StringDlg.cpp
	Dlgs/TextureSearchReplaceDlg.cpp
	Dlgs/TextureTrackerDlg.cpp
	Dlgs/UndoWarningDlg.cpp
	Dlgs/WorldInfoDlg.cpp
	Docs/PropertyHelpers.cpp
	Docs/RegionDoc.cpp
	draw/CCS.cpp
	draw/d3d_texturemgr.cpp
	draw/DibBuffer.cpp
	draw/DrawBase.cpp
	draw/draw_d3d.cpp
	draw/Navigator.cpp
	draw/UsefulDC.cpp
	draw/UsefulDib.cpp
	draw/ViewDef.cpp
	FileFormats/CObjInterface.cpp
	Frames/ChildFrm.cpp
	Frames/coolbar.cpp
	Frames/DEDockFrameWnd.cpp
	Frames/flattoolbar.cpp
	Frames/MainFrm.cpp
	Frames/RegionFrame.cpp
	KeyAggregate/KeyDefaultAggregate.cpp
	KeyAggregate/KeyDefaultFactory.cpp
	LevelError/Detectors.cpp
	LevelError/ErrorDetector.cpp
	LevelError/LevelError.cpp
	LevelError/LevelErrorDB.cpp
	Lightmap/DEditLightMapMgr.cpp
	Lightmap/HolderList.cpp
	Lightmap/LightMapAllocator.cpp
	Lightmap/LightMapData.cpp
	Lightmap/LightMapGenerator.cpp
	Lightmap/LMSampleGen.cpp
	Lightmap/ShadowCalc.cpp
	Lightmap/SurfaceLMTextureMgr.cpp
	Misc/EditHelpers.cpp
	Misc/EditorTransfer.cpp
	Misc/FileUtils.cpp
	Misc/Splash.cpp
	Misc/Texture.cpp
	ModelView/meshshape.cpp
	ModelView/meshshapelist.cpp
	ModelView/modelmesh.cpp
	ModelView/modelmgr.cpp
	MRCEXT/DRAGDOCK.CPP
	MRCEXT/FRAMEWND.CPP
	MRCEXT/MDIFLOAT.CPP
	MRCEXT/MRCButton.cpp
	MRCEXT/SIZECONT.CPP
	MRCEXT/SIZEDLG.CPP
	MRCEXT/SIZEDOCK.CPP
	MRCEXT/SZTOOLBA.CPP
	Options/DEditOptions.cpp
	Options/OptionsAdvancedSelect.cpp
	Options/OptionsBase.cpp
	Options/OptionsClassDialog.cpp
	Options/OptionsClipboard.cpp
	Options/OptionsControls.cpp
	Options/OptionsDisplay.cpp
	Options/OptionsGenerateUniqueNames.cpp
	Options/OptionsLighting.cpp
	Options/OptionsMisc.cpp
	Options/OptionsModels.cpp
	Options/OptionsObjectBrowser.cpp
	Options/OptionsPrefabs.cpp
	Options/OptionsPrimitives.cpp
	Options/OptionsRun.cpp
	Options/OptionsViewports.cpp
	Options/OptionsWarnings.cpp
	Options/OptionsWindows.cpp
	Project/d_filemgr.cpp
	Project/EditProjectMgr.cpp
	RegionEdit/AdvancedSelect.cpp
	RegionEdit/CreatePrimitive.cpp
	RegionEdit/EditClipboard.cpp
	RegionEdit/EditGrid.cpp
	RegionEdit/edit_actions.cpp
	RegionEdit/Refs.cpp
	RegionEdit/undo_mgr.cpp
	RegionEdit/ViewFunctions.cpp
	RegionEdit/viewrender.cpp
	Trackers/RVCommand.cpp
	Trackers/RVTracker.cpp
	Trackers/RVTrackerBrushSize.cpp
	Trackers/RVTrackerCurveEdit.cpp
	Trackers/RVTrackerDrawPoly.cpp
	Trackers/RVTrackerExtrudePoly.cpp
	Trackers/RVTrackerFarDist.cpp
	Trackers/RVTrackerFocus.cpp
	Trackers/RVTrackerGridSize.cpp
	Trackers/RVTrackerMarkerMove.cpp
	Trackers/RVTrackerMenuItem.cpp
	Trackers/RVTrackerNavArcRotate.cpp
	Trackers/RVTrackerNavDrag.cpp
	Trackers/RVTrackerNavMove.cpp
	Trackers/RVTrackerNavOrbit.cpp
	Trackers/RVTrackerNavRotate.cpp
	Trackers/RVTrackerNodeMove.cpp
	Trackers/RVTrackerNodeRotate.cpp
	Trackers/RVTrackerObjectSize.cpp
	Trackers/RVTrackerPolyScale.cpp
	Trackers/RVTrackerTag.cpp
	Trackers/RVTrackerTextMove.cpp
	Trackers/RVTrackerTextWrap.cpp
	Trackers/RVTrackerVertMove.cpp
	Trackers/RVTrackerVertScale.cpp
	Trackers/RVTrackerVertSnap.cpp
	Trackers/RVTrackerZoom.cpp
	Trackers/TrackerMgr.cpp
	Views/RegionView.cpp
	Views/RegionViewInitTracker.cpp
	../../runtime/kernel/src/sys/win/streamsim.cpp
	../../runtime/shared/src/version_info.cpp
	../shared/engine/geomroutines.cpp
	../shared/engine/dtxmgr.cpp
	../shared/engine/pixelformat.cpp
	../shared/engine/simple_dalloc.cpp
	../shared/engine/genltstream.cpp
	../shared/engine/dhashtable.cpp
	../shared/engine/classbind.cpp
	../shared/engine/bindmgr.cpp
	../shared/engine/dsys_interface.cpp
	../shared/engine/version_resource.cpp
	../shared/engine/concommand.cpp
	../shared/engine/bdefs.cpp
	../shared/model/ltaScene.cpp
	../../sdk/inc/ltquatbase.cpp)

target_sources(${PROJECT_NAME}
	PRIVATE dedit.rc)

set_target_properties(${PROJECT_NAME}
	PROPERTIES OUTPUT_NAME DEdit)

include_directories(./
	../../runtime/kernel/src
	../shared/engine
	../../libs/stdlith
	../../sdk/inc
	../PreProcessor
	../shared/world
	../dedit/misc
	Controls
	Dlgs
	Docs
	draw
	FileFormats
	Frames
	KeyAggregate
	LevelError
	Lightmap
	ModelView
	MRCEXT
	Options
	Project
	RegionEdit
	res
	Trackers
	Views
	../../libs/genregmgr
	../../libs/butemgr
	../../libs/dibmgr
	../../libs/cryptmgr
	../../libs/regmgr
	../../libs/lith
	../../libs/ltamgr
	../../libs/rezmgr
	../shared/model
	MRCEXT/VC_HEADERS
	${SDL2_INCLUDE_DIRS})

target_link_libraries(${PROJECT_NAME}
	LIB_StdLith
	LIB_ButeMgr
	LIB_ToolModel
	LIB_CryptMgr
	LIB_GenRegMgr
	LIB_ToolWorld
	LIB_ltamgr
	LIB_dibmgr
	LIB_RezMgr
	LIB_RegMgr
	s3tc
	winmm
	ddraw
	dxguid)

set_target_properties(${PROJECT_NAME} PROPERTIES LINK_FLAGS "/SAFESEH:NO /NODEFAULTLIB:libcmtd.lib /NODEFAULTLIB:libc.lib")	# needed for s3tc.lib :/
