#ifndef USE_FOLDERCOMMANDS
#define USE_FOLDERCOMMANDS

///////////////////////////////////////
// The command IDs for the folder options

enum eFolderCmds
{
	FOLDER_CMD_NONE,
	FOLDER_CMD_LEFT_ARROW,
	FOLDER_CMD_RIGHT_ARROW,
	FOLDER_CMD_UP_ARROW,
	FOLDER_CMD_DOWN_ARROW,

// Main folder
	FOLDER_CMD_SINGLE_PLAYER,
	FOLDER_CMD_MULTIPLAYER,
	FOLDER_CMD_MULTIPLAYER_LAN,
	FOLDER_CMD_RESUME,
	FOLDER_CMD_CONTINUE_GAME,
	FOLDER_CMD_PROFILE,
	FOLDER_CMD_OPTIONS,
	FOLDER_CMD_QUIT,	// Brings up the confirmation dialog
	FOLDER_CMD_EXIT,	// Actually quits the game

// Single player
	FOLDER_CMD_NEW_GAME,
	FOLDER_CMD_LOAD_GAME,
	FOLDER_CMD_SAVE_GAME,
	FOLDER_CMD_CUSTOM_LEVEL,
	FOLDER_CMD_FAVORITE_LEVEL,
	FOLDER_CMD_MARINE_MODE,
	FOLDER_CMD_PREDATOR_MODE,
	FOLDER_CMD_ALIEN_MODE,

// Multi player
	FOLDER_CMD_MP_HOST,
	FOLDER_CMD_MP_JOIN,
	FOLDER_CMD_MP_JOIN_LAN,
	FOLDER_CMD_MP_JOIN_GAME,
	FOLDER_CMD_MP_INFO,
	FOLDER_CMD_MP_SETUP,
	FOLDER_CMD_MP_MAPS,
	FOLDER_CMD_MP_PLAYER,
	FOLDER_CMD_MP_PLAYER_JOIN,
	FOLDER_CMD_MP_ADVANCED,
	FOLDER_CMD_MP_CONFIG,

// Options
	FOLDER_CMD_DIFFICULTY,
	FOLDER_CMD_DISPLAY,
	FOLDER_CMD_AUDIO,
	FOLDER_CMD_CONTROLS,
	FOLDER_CMD_GAME,
	FOLDER_CMD_PERFORMANCE,

// Profile
	FOLDER_CMD_ACTIVATE_PROFILE,

// Display
	FOLDER_CMD_RENDERER,
	FOLDER_CMD_CHOOSE_RENDERER,
	FOLDER_CMD_RESOLUTION,
	FOLDER_CMD_CHOOSE_RESOLUTION,

// Controls
	FOLDER_CMD_CUSTOM_CONTROLS,
	FOLDER_CMD_MOUSE,
	FOLDER_CMD_KEYBOARD,
	FOLDER_CMD_JOYSTICK,
	FOLDER_CMD_ADV_CONTROLS,
	FOLDER_CMD_CHANGE_CONTROL,
	FOLDER_CMD_RESET_DEFAULTS,
	FOLDER_CMD_CROSSHAIR,
	FOLDER_CMD_ALIEN_CONFIG,
	FOLDER_CMD_MARINE_CONFIG,
	FOLDER_CMD_PREDATOR_CONFIG,

// Selection
	FOLDER_CMD_SELECT_SLOT,
	FOLDER_CMD_SELECT_ITEM,

//	Reusable
	FOLDER_CMD_LAUNCH,
	FOLDER_CMD_BACK,
	FOLDER_CMD_CONTINUE,
	FOLDER_CMD_MAIN,
	FOLDER_CMD_BREAK,
	FOLDER_CMD_UPDATE,
	FOLDER_CMD_PASSWORD,
	FOLDER_CMD_CUSTOM, //this needs to be the last cmd, so that custom commands may be defined after it
};



#endif
